### ISSUE TITLE
端口数多了出现这个 即使降低线程

### ISSUE THREAD

**Issue by thelostworldFree** [qianxiao996/Super-PortScan#1]
![image](https://user-images.githubusercontent.com/24971604/122675933-51e0e380-d20e-11eb-8725-44423527bdd5.png)
端口数多了出现这个 即使降低线程

**Comment by qianxiao996** [comment]
这个是因为命令行的原因，请换个命令行试一下。

**Comment by yy2511** [comment]
![image](https://user-images.githubusercontent.com/66409032/123607557-954fd900-d830-11eb-95fd-de0056a18cb7.png)
为什么一直提示这个

**Comment by qianxiao996** [comment]
缺少scapy包,请运行pip install scapy 安装
