### ISSUE TITLE
需要安装什么环境吗，运行不起来

### ISSUE THREAD

**Issue by yfwb** [qianxiao996/Super-PortScan#3]

**Comment by qianxiao996** [comment]
exe版本不需要什么环境 py的话你得看看缺什么包



***@***.***
 
发件人： yfwb
发送时间： 2022-05-27 09:47
收件人： qianxiao996/Super-PortScan
抄送： Subscribed
主题： [qianxiao996/Super-PortScan] 需要安装什么环境吗，运行不起来 (Issue #3)
―

**Comment by yfwb** [comment]
不少报错，需要pip安装一些包，可以了，谢谢
