### ISSUE TITLE
改写成周期性运行会报错

### ISSUE THREAD

**Issue by xiaqiqi-1** [qianxiao996/Super-PortScan#4]
运行环境：ubuntu20.04
把程序周期性运行起来会造成报错：[Errno 24] Too many open files----699行
while 1:
    portscan=PortScan.Portscan()
    portscan.chuli_canshu('','ip.txt','','port.txt','','','',1,'',400,'1.txt','')
    f=open('1.txt','w')
    f.close()
调用程序是这么写的

**Comment by qianxiao996** [comment]
同时打开文件太多了，你这个直接无限循环了。

**Comment by xiaqiqi-1** [comment]
原本预期是想要端口扫描程序持续的运行下去，但是发现随着portscan调用次数，程序在linux运行下所占用的文件句柄数会越多，当超过linux限制的参数时，程序就会报错，但是所有文件打开都有着对应的colse操作，应该在调用完成后会释放掉占用文件句柄数。

**Comment by qianxiao996** [comment]
file_cls = open(port_file_path, 'r', encoding='utf-8')
                data = file_cls.read()

这个没关闭。

**Comment by xiaqiqi-1** [comment]
> ```
>             file_cls = open(port_file_path, 'r', encoding='utf-8')
>             data = file_cls.read()
> ```
> 
> 这个没关闭。
问题依然存在，报错代码是在eventlet.monkey_patch(thread=False, time=True)这个代码处，打开的文件时输出的txt结果文件
